/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface LanguageInfo {
  lang: string
  lines: number
  code: number
  comments: number
  blanks: number
}
export interface Report {
  name: string
  status: Array<CodeStatus>
}
export interface CodeStatus {
  blanks: number
  code: number
  comments: number
}
export interface TokeiOptions {
  include?: Array<string>
  exclude?: Array<string>
  languages?: Array<string>
}
export function tokei(options: TokeiOptions): Array<LanguageInfo>
