/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface Langs {
  lang: string
  lines: number
  code: number
  comments: number
  blanks: number
}
export interface Report {
  name: string
  status: Array<CodeStatus>
}
export interface CodeStatus {
  blanks: number
  code: number
  comments: number
}
export interface Options {
  include?: Array<string>
  exclude?: Array<string>
  langs?: Array<string>
}
export function tokei(options: Options): Array<Langs>
