/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface Langs {
  name: string
  code: number
}
export interface Report {
  name: string
  status: Array<CodeStatus>
}
export interface CodeStatus {
  blanks: number
  code: number
  comments: number
}
export function tokei(): Array<Langs>
